[package]
name = "ttp_forwarder"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
libc = "0.2.171"
md5 = "0.7.0"
nix = { version = "0.29.0", features = ["socket"] }
socket2 = "0.5.9"
toml = "0.8.20"
